from gensim.models import Word2Vec
import argparse
import json
import gzip


parser = argparse.ArgumentParser()
parser.add_argument('--cleaned_word_list',dest = 'cleaned_word_list',help = 'cleaned word list generated by data_cleaning.py')
parser.add_argument('--output_model',dest = 'output_model',help = 'trained Word2Vec model')
args = parser.parse_args()

# to add
# open args.clean_word_list (json file)
# load into variable x
# sentences = x
# run 2 times, one for each time window

model = Word2Vec(sentences = args.cleaned_word_list, vector_size = 100, window = 5, min_count = 1, workers = 4)
model.save(args.output_model)